# Generated by Django 3.2.7 on 2021-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0003_auto_20210922_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_vonr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
