# Generated by Django 3.2.7 on 2021-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0004_alter_call_call_vonr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='call_business_direction_ter',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_csfb',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_epsfb',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_volte',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_vonr',
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_dut_csfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_dut_epsfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_dut_volte',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_dut_vonr',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_ref_csfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_ref_epsfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_ref_volte',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mo_ref_vonr',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_dut_csfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_dut_epsfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_dut_volte',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_dut_vonr',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_ref_csfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_ref_epsfb',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_ref_volte',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='voicecall_mt_ref_vonr',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
