# Generated by Django 3.2.7 on 2021-09-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0005_auto_20210923_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_operator', models.CharField(max_length=200)),
                ('dut_cf', models.FloatField(blank=True, max_length=200, null=True)),
                ('dut_cb', models.FloatField(blank=True, max_length=200, null=True)),
                ('dut_cw', models.FloatField(blank=True, max_length=200, null=True)),
                ('fttest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dept.fttest')),
            ],
        ),
    ]
