# Generated by Django 3.2.7 on 2021-09-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0007_auto_20210924_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTFF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_person', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('test_branch', models.CharField(max_length=200)),
                ('test_location', models.CharField(max_length=200)),
                ('setup_pattern', models.CharField(max_length=200)),
                ('search_pattern', models.CharField(max_length=200)),
                ('dut1', models.FloatField(blank=True, max_length=200, null=True)),
                ('dut2', models.FloatField(blank=True, max_length=200, null=True)),
                ('ref', models.FloatField(blank=True, max_length=200, null=True)),
                ('stdvalues', models.FloatField(blank=True, max_length=200, null=True)),
                ('result', models.BooleanField()),
            ],
        ),
    ]
