# Generated by Django 3.2.7 on 2021-09-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0010_auto_20210926_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name_plural': '通话业务表'},
        ),
        migrations.AlterModelOptions(
            name='fttest',
            options={'verbose_name_plural': '场测测试表'},
        ),
        migrations.AlterModelOptions(
            name='ss',
            options={'verbose_name_plural': '补充业务表'},
        ),
        migrations.AlterModelOptions(
            name='ttff',
            options={'verbose_name_plural': 'GNSS_TTFF业务表'},
        ),
    ]
