# Generated by Django 3.2.7 on 2021-09-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dept', '0011_auto_20210927_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': '通话业务', 'verbose_name_plural': '通话业务表'},
        ),
        migrations.AlterModelOptions(
            name='fttest',
            options={'verbose_name': '场测任务', 'verbose_name_plural': '场测测试表'},
        ),
        migrations.AlterModelOptions(
            name='ss',
            options={'verbose_name': '补充业务', 'verbose_name_plural': '补充业务表'},
        ),
        migrations.AlterModelOptions(
            name='ttff',
            options={'verbose_name': 'TTFF', 'verbose_name_plural': 'GNSS_TTFF业务表'},
        ),
    ]
